/*
 * This source file was generated by the Gradle 'init' task
 */
//package ppfootballmanager;

//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

//class AppTest {
   // @Test void appHasAGreeting() {
     //   FootballManagerApp classUnderTest = new FootballManagerApp();
       // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    //}
//}
